/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectTools;

import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Hashtable;
import javax.swing.JRadioButton;

/**
 *
 * @author taleb
 */
public class ModalOptionDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = -763955528824272241L;

    /**
     * Creates new form ModalOptionDialog
     *
     * @param parent
     * @param modal
     */
    public ModalOptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        options = new Hashtable<>();
        jScrollPane1.getHorizontalScrollBar().setUI(new WindowsScrollBarUI());
    }

    private int selectedOptionValue;

    public int getSelectedOptionValue() {
        return selectedOptionValue;
    }

    private Hashtable<Integer,JRadioButton> options;
    
    public void addOption(String optionName, int optionValue) {

        JRadioButton jRadioOption = new JRadioButton(optionName);
        jRadioOption.setBackground(Color.white);
        jRadioOption.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                selectedOptionValue = optionValue;
            }
        });
        GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 22);
        jPanel2.add(jRadioOption, gridBagConstraints);
        buttonGroup1.add(jRadioOption);
        options.put(optionValue, jRadioOption);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelValider = new javax.swing.JLabel();
        jLabelAnnuler = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jPanel2);

        jLabelValider.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabelValider.setForeground(new java.awt.Color(0, 102, 102));
        jLabelValider.setText("Valider");
        jLabelValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelValiderMouseClicked(evt);
            }
        });

        jLabelAnnuler.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabelAnnuler.setForeground(new java.awt.Color(0, 0, 102));
        jLabelAnnuler.setText("Annuler");
        jLabelAnnuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAnnulerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabelAnnuler)
                .addGap(64, 64, 64)
                .addComponent(jLabelValider)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValider)
                    .addComponent(jLabelAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int userAnswer;
    public static final int USER_YES = 1;
    public static final int USER_NO = 0;

    private void jLabelValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelValiderMouseClicked
        // TODO add your handling code here:
        userAnswer = USER_YES;
        dispose();
    }//GEN-LAST:event_jLabelValiderMouseClicked

    private void jLabelAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnnulerMouseClicked
        // TODO add your handling code here:
        userAnswer = USER_NO;
        dispose();
    }//GEN-LAST:event_jLabelAnnulerMouseClicked

    public int getUserAnswer() {
        return userAnswer;
    }

    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelAnnuler;
    private javax.swing.JLabel jLabelValider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void selectedOption(int selectedOption) {
        options.get(selectedOption).setSelected(true); //To change body of generated methods, choose Tools | Templates.
    }
}
