/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectTools;

import javax.swing.ImageIcon;

/**
 * ModalInputDialogue est une fenetre qui herite du JDialog une class java qui as deja la modalité implementé
 * 
 * 
 * une classe est COMPORTEMENTAL ( sois elle decris qlq chose , sois elle fait qlq chose )
 * @author taleb
 */
public class ModalInputDialog extends javax.swing.JDialog {

    // ceci n est pas important pour l instant il me servira apres dans le logger des erreurs mais pas maintenant
    private static final long serialVersionUID = 6189532355855057171L;
    
    // user answer veux dire la reponse de mon utilisateur j ai devlarer cette variable pour quel sois la variable qui va garder 
    // la reponse de mon utilisateur
    
    private int userAnswer;
    
    public static final int USER_YES = 1; // je declare cette constante pour Valider
    public static final int USER_NO = 0; // je  declare cella pour annuler
    
    /**
     * Creates new form ErrorDialog
     * ici c est le fameu constructeur
     * 
     * le constructeur permet l instanciation de mon abjet dans notre cas une fenetre de type JDIALOGUE
     * 
     * dans java on as JDialog et JFrame les deux qui represente des fenetres
     * seulement JDialogue a l'option MODAL active tanque JFrame nous permet de cliquer sur n'importe quel fenetre
     * ( ce que je te dit la est un abrégé sur la modalité, en detail la modalité peu etre implementable par bruteCode:
     * bruteCode veux dire qu on va nous meme creer un code qui permet a un JFrame d'etre MODAL ) mais bon JDialog existe pour 
     * cette raison
     * 
     * @param parent
     * @param modal
     */
    public ModalInputDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal); // construction par heritage afin de construire tout ce qui est dans JDIALOG
        initComponents();// init component cette methode contient toutes les instanciation des composant graphic
        this.setLocationRelativeTo(null);// cette methode permet d'afficher en milleur de l ecrant
    }

    public void showErrorDialog(String errorMessage){
     txt.setText(errorMessage);
     icon.setIcon(new ImageIcon(getClass().getResource("icons8_Error_96px.png")));
     setVisible(true);
    }
    
    public void showWarningDialog(String warningMessage){
     txt.setText(warningMessage);
     icon.setIcon(new ImageIcon(getClass().getResource("icons8_Warning_Shield_96px.png")));
     setVisible(true);
    }
    
    public void showConfirmDialog(String confirmMessage){
     txt.setText(confirmMessage);
     icon.setIcon(new ImageIcon(getClass().getResource("icons8_Ok_Hand_96px.png")));
     setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * La traduction :
     * cette methode ets appelé depuis le constructeur pour initialise la fenetre est ses composant
     * Attention : a ne pas toucher ni modifier, le  contenu de cette methode est auto generé par l 'editeur de fenetre
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        txt.setEditable(false);
        txt.setBorder(null);
        txt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(45, 45, 45));
        txt.setText("lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis lorum epsum vandis ");
        txt.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane1.setViewportView(txt);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Valider");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Annuler");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        userAnswer = USER_YES;
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    public int getUserAnswer() {
        return userAnswer;
    }
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        userAnswer = USER_NO;
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txt;
    // End of variables declaration//GEN-END:variables
}
