/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectTools;

import java.awt.ComponentOrientation;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.function.Predicate;
import java.util.stream.Collectors;
import javax.swing.ListModel;

/**
 *
 * @author taleb
 * @param <T>
 */
public class ModalListDialog<T> extends javax.swing.JDialog {

    private static final long serialVersionUID = 6189532355855057171L;
    private int userAnswer;
    public static final int USER_YES = 1;
    public static final int USER_NO = 0;
    private Predicate<? super T> prdct;
    /**
     * Creates new form ErrorDialog
     * @param parent
     * @param modal
     */
    public ModalListDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void setSearchPredecate(Predicate<? super T> prdct){
        this.prdct = prdct;
    }
    
    public void addJListMouseClickedEvent(MouseListener ml){
        jList1.addMouseListener(ml);
    }
    
    public  void showArabicModalList(ListModel lm){
        jList1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        PlaceHolderDecorator.decorate(jTextField1, "البحث");
        jLabelValider.setText("موافق");
        jLabelAnnuler.setText("إلغاء");
        this.lm = (EntityListModel) lm ;
        jList1.setModel(lm);
        setVisible(true);
        
    }
    
    private EntityListModel<T> lm;
    
    public void showFrench(ListModel lm){
        jList1.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        PlaceHolderDecorator.decorate(jTextField1, "Recherche");
        jLabelValider.setText("Valider");
        jLabelAnnuler.setText("Annuler");
        jList1.setModel(lm);
        this.lm = (EntityListModel) lm ;
        setVisible(true);
        
    }
    
    public void setValidationEvent(MouseListener ml){
        jLabelValider.addMouseListener(ml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelValider = new javax.swing.JLabel();
        jLabelAnnuler = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelValider.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabelValider.setForeground(new java.awt.Color(0, 102, 102));
        jLabelValider.setText("Valider");
        jLabelValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelValiderMouseClicked(evt);
            }
        });

        jLabelAnnuler.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jLabelAnnuler.setForeground(new java.awt.Color(0, 0, 102));
        jLabelAnnuler.setText("Annuler");
        jLabelAnnuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAnnulerMouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jList1.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectTools/icons8_Search_32px_1.png"))); // NOI18N

        jTextField1.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabelAnnuler)
                .addGap(64, 64, 64)
                .addComponent(jLabelValider)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValider)
                    .addComponent(jLabelAnnuler))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelValiderMouseClicked
        // TODO add your handling code here:
        userAnswer = USER_YES;
        dispose();
    }//GEN-LAST:event_jLabelValiderMouseClicked

    public int getUserAnswer() {
        return userAnswer;
    }
    
    private void jLabelAnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAnnulerMouseClicked
        // TODO add your handling code here:
        userAnswer = USER_NO;
        dispose();
    }//GEN-LAST:event_jLabelAnnulerMouseClicked

    public String getSearchText(){
        return jTextField1.getText().toLowerCase();
    }
    
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
System.out.println("search start");
        if (getSearchText().trim().isEmpty()) {
            System.out.println("search empty");
            jList1.setModel(lm);
        }else{
            System.out.println("search full");
            List<T> collect = lm.getEntities().stream().filter(prdct).collect(Collectors.toList());
            EntityListModel<T> elm = new  EntityListModel<>();
            collect.stream().forEach(cnsmr->{elm.addDistinct(cnsmr);});
            jList1.setModel(elm);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAnnuler;
    private javax.swing.JLabel jLabelValider;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public T getSelectedElement() {
        return lm.getElementAt(jList1.getSelectedIndex());
    }

    public void refreshList(EntityListModel<T> listModel) {
        jList1.setModel(listModel);
        lm=listModel;
    }
}
