/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * @author taleb
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "Candidat.findByName", query = "Select e from Candidat e where e.candidatInfo.nom = :nom"),
    @NamedQuery(name = "Candidat.findByPrenom", query = "Select e from Candidat e where e.candidatInfo.prenom = :prenom"),
    @NamedQuery(name = "Candidat.findByOccurence", query = "Select e from Candidat e WHERE e.candidatInfo.nom = :nom AND e.candidatInfo.prenom = :prenom AND e.candidatInfo.dateNaissance = :dateNaissance")})

public class Candidat implements Serializable {
    
    private static final long serialVersionUID = 6848482521697996546L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Candidat other = (Candidat) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Embedded
    private CandidatInfo candidatInfo;

    @OneToMany(targetEntity = Inscription.class)
    private List<Inscription> inscriptions;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CandidatInfo getCandidatInfo() {
        return this.candidatInfo;
    }

    public void setCandidatInfo(CandidatInfo candidatInfo) {
        this.candidatInfo = candidatInfo;
    }

    public List<Inscription> getInscriptions() {
        return this.inscriptions;
    }

    public void setInscriptions(List<Inscription> inscriptions) {
        this.inscriptions = inscriptions;
    }

    @Override
    public String toString() {
        return candidatInfo.toString() ;
    }
 
    
}
