/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author taleb
 */
@Entity
public class Ecole implements Serializable {

    private static final long serialVersionUID = 7531476414067586347L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String nom;

    @Basic
    private String num;

    @Basic
    private String wilaya;

    @ElementCollection
    private List<String> moniteurs;

    @ElementCollection
    private List<String> matricules;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getNum() {
        return this.num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getWilaya() {
        return this.wilaya;
    }

    public void setWilaya(String wilaya) {
        this.wilaya = wilaya;
    }

    public List<String> getMoniteurs() {
        return this.moniteurs;
    }

    public void setMoniteurs(List<String> moniteurs) {
        this.moniteurs = moniteurs;
    }

    public List<String> getMatricules() {
        return this.matricules;
    }

    public void setMatricules(List<String> matricules) {
        this.matricules = matricules;
    }

}
