/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import java.util.Date;
import javafx.util.converter.DateStringConverter;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author taleb
 */
@Entity
public class Examen implements Serializable {

    private static final long serialVersionUID = -2028860925985027930L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateExamen;

    @OneToOne(targetEntity = Examinateur.class)
    private Examinateur examinateur;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getDateExamen() {
        return this.dateExamen;
    }

    public void setDateExamen(Date dateExamen) {
        this.dateExamen = dateExamen;
    }

    public Examinateur getExaminateur() {
        return this.examinateur;
    }

    public void setExaminateur(Examinateur examinateur) {
        this.examinateur = examinateur;
    }

    @Override
    public String toString() {
        return  new DateStringConverter("dd-MM-yyyy").toString(dateExamen) + ":" + examinateur.getExaminateurInfo();
    }

}
