/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author taleb
 */
@Entity
public class Examinateur implements Serializable {

    private static final long serialVersionUID = 9203628280491814609L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Embedded
    private CandidatInfo examinateurInfo;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CandidatInfo getExaminateurInfo() {
        return this.examinateurInfo;
    }

    public void setExaminateurInfo(CandidatInfo examinateurInfo) {
        this.examinateurInfo = examinateurInfo;
    }

}
