/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author taleb
 */
@Entity
public class Inscription implements Serializable {

    private static final long serialVersionUID = -7900679017540876231L;

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Inscription other = (Inscription) obj;
        return Objects.equals(this.id, other.id);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @Enumerated(EnumType.STRING)
    private CategoriePermis categoriePermis;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date dateInscription;

    public Long getId() { // ici par exemple j ai une fonction qui n as pas 
                    //de paramettre mais qui a un type de retour Long cette fonction refait TJR la meme chose
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CategoriePermis getCategoriePermis() {
        return this.categoriePermis;
    }

    public void setCategoriePermis(CategoriePermis categoriePermis) {
        this.categoriePermis = categoriePermis;
    }

    public Date getDateInscription() {
        return this.dateInscription;
    }

    public void setDateInscription(Date dateInscription) {
        this.dateInscription = dateInscription;
    }

}
