/**
 * This file was generated by the JPA Modeler
 */
package entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * @author taleb
 */
@Entity
public class Printable implements Serializable {

    @Id
    private Long id;

    @Basic
    private Long printID;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPrintID() {
        return this.printID;
    }

    public void setPrintID(Long printID) {
        this.printID = printID;
    }

}
