/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.candidat;

import java.awt.Color;
import java.awt.Component;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import javax.swing.JLabel;
import projectTools.PlaceHolderDecorator;

/**
 *
 * @author taleb
 */
public class FormCandidat extends javax.swing.JDialog {

    private static final long serialVersionUID = 1192686827455183342L;

    /**
     * Creates new form FormCandidat
     */
    final private FormCondidatController controller;

    public FormCandidat(FormCondidatController condidatController) {
        initComponents();
        setModal(true);
        controller = condidatController;
        jList1.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        PlaceHolderDecorator.decorate(jTextField1, jTextField1.getText(), Color.GRAY, Color.black);
        Component[] components = jList1.getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                ((JLabel) component).setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlbNom = new javax.swing.JLabel();
        jlbDtNaissance = new javax.swing.JLabel();
        jlbPermiDeman = new javax.swing.JLabel();
        jlbExame = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlbNumTelephone = new javax.swing.JLabel();
        jlbLieuNaissance = new javax.swing.JLabel();
        jlbAdresse = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jlbDtInscr = new javax.swing.JLabel();
        jlbNationalite = new javax.swing.JLabel();
        jlbNomValue = new javax.swing.JLabel();
        jlbdtNaissanceValue = new javax.swing.JLabel();
        jlbNumTelValue = new javax.swing.JLabel();
        jlbAdresseValue = new javax.swing.JLabel();
        jlbPermisValue = new javax.swing.JLabel();
        jlbLieuNaissanceValue = new javax.swing.JLabel();
        jlbNationaliteValue3 = new javax.swing.JLabel();
        jlbdtInscValue = new javax.swing.JLabel();
        jlbExamenValue = new javax.swing.JLabel();
        jlbNom1 = new javax.swing.JLabel();
        jlbNom2 = new javax.swing.JLabel();
        jlbNomPereValue = new javax.swing.JLabel();
        jlbNomMereValue = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 188, 0));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons/icons8_Home_32px_1.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/icons/icons8_Enter_32px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/candidat/5.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(20, 6, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNom.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbNom.setForeground(new java.awt.Color(204, 204, 0));
        jlbNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNom.setText("اللقب و الاسم :");
        jPanel5.add(jlbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, 32));

        jlbDtNaissance.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbDtNaissance.setForeground(new java.awt.Color(204, 204, 0));
        jlbDtNaissance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDtNaissance.setText("تاريخ الازدياد :");
        jPanel5.add(jlbDtNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 30));

        jlbPermiDeman.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbPermiDeman.setForeground(new java.awt.Color(204, 204, 0));
        jlbPermiDeman.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbPermiDeman.setText("الرخصة :");
        jPanel5.add(jlbPermiDeman, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 32));

        jlbExame.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbExame.setForeground(new java.awt.Color(204, 204, 0));
        jlbExame.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbExame.setText("Examen en cours :");
        jPanel5.add(jlbExame, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 312, -1, 32));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 29, -1, 315));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/candidat/icons8_Reduce_32px_1.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 169, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/candidat/icons8_Registration_32px.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 119, -1, -1));

        jlbNumTelephone.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbNumTelephone.setForeground(new java.awt.Color(204, 204, 0));
        jlbNumTelephone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNumTelephone.setText("رقم الهاتف :");
        jPanel5.add(jlbNumTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 32));

        jlbLieuNaissance.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbLieuNaissance.setForeground(new java.awt.Color(204, 204, 0));
        jlbLieuNaissance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbLieuNaissance.setText("مكان الازدياد :");
        jPanel5.add(jlbLieuNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 32));

        jlbAdresse.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbAdresse.setForeground(new java.awt.Color(204, 204, 0));
        jlbAdresse.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbAdresse.setText("العنوان :");
        jPanel5.add(jlbAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 32));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 258, 564, 10));

        jlbDtInscr.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbDtInscr.setForeground(new java.awt.Color(204, 204, 0));
        jlbDtInscr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbDtInscr.setText("تاريخ الانخراط :");
        jPanel5.add(jlbDtInscr, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, 32));

        jlbNationalite.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbNationalite.setForeground(new java.awt.Color(204, 204, 0));
        jlbNationalite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNationalite.setText("الجنسية :");
        jPanel5.add(jlbNationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, 32));

        jlbNomValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbNomValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbNomValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 29, 460, 32));

        jlbdtNaissanceValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbdtNaissanceValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbdtNaissanceValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbdtNaissanceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 110, 190, 32));

        jlbNumTelValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbNumTelValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbNumTelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbNumTelValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 160, 160, 32));

        jlbAdresseValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbAdresseValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbAdresseValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbAdresseValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 490, 32));

        jlbPermisValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbPermisValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbPermisValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbPermisValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 30));

        jlbLieuNaissanceValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbLieuNaissanceValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbLieuNaissanceValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbLieuNaissanceValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, 32));

        jlbNationaliteValue3.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbNationaliteValue3.setForeground(new java.awt.Color(255, 255, 255));
        jlbNationaliteValue3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbNationaliteValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 220, 32));

        jlbdtInscValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbdtInscValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbdtInscValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbdtInscValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 270, 250, 32));

        jlbExamenValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbExamenValue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jlbExamenValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 312, -1, 32));

        jlbNom1.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbNom1.setForeground(new java.awt.Color(204, 204, 0));
        jlbNom1.setText("و :");
        jPanel5.add(jlbNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 30));

        jlbNom2.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jlbNom2.setForeground(new java.awt.Color(204, 204, 0));
        jlbNom2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbNom2.setText("إبن :");
        jPanel5.add(jlbNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 40, 30));

        jlbNomPereValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbNomPereValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomPereValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbNomPereValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 70, 220, 30));

        jlbNomMereValue.setFont(new java.awt.Font("Simplified Arabic", 0, 18)); // NOI18N
        jlbNomMereValue.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomMereValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jlbNomMereValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 260, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(20, 6, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("البحث");
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/candidat/icons8_Search_32px_1.png"))); // NOI18N

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 45, 45)));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jList1.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(45, 45, 45));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Chargement en cours ..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jList1.setSelectionBackground(new java.awt.Color(247, 243, 178));
        jList1.setSelectionForeground(new java.awt.Color(8, 8, 8));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/candidat/icons8_Plus_2_Math_32px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        controller.doshowAddCandidat();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
         controller.getListCandidat(jList1);
       
    }//GEN-LAST:event_formWindowGainedFocus
   

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        final int selectedIndex = jList1.getSelectedIndex();
        // TODO add your handling code here:
        if (selectedIndex == -1) {
            return;
        }

        controller.showSelectedCandidat(jList1, selectedIndex, jlbAdresseValue, jlbNomValue,
                jlbdtNaissanceValue, jlbNomPereValue, jlbNomMereValue, jlbNumTelValue, jlbExamenValue,
                jlbPermisValue, jlbdtInscValue, jlbLieuNaissanceValue, jlbNationaliteValue3);

        pack();
    }//GEN-LAST:event_jList1ValueChanged


    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        doDelete();
    }//GEN-LAST:event_jLabel13MouseClicked

    public void doDelete() throws HeadlessException {

        controller.remove(jList1);
    }

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:

        controller.doSearch(jTextField1, jList1);

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        controller.doshowEditCandidat(jList1);
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbAdresse;
    private javax.swing.JLabel jlbAdresseValue;
    private javax.swing.JLabel jlbDtInscr;
    private javax.swing.JLabel jlbDtNaissance;
    private javax.swing.JLabel jlbExame;
    private javax.swing.JLabel jlbExamenValue;
    private javax.swing.JLabel jlbLieuNaissance;
    private javax.swing.JLabel jlbLieuNaissanceValue;
    private javax.swing.JLabel jlbNationalite;
    private javax.swing.JLabel jlbNationaliteValue3;
    private javax.swing.JLabel jlbNom;
    private javax.swing.JLabel jlbNom1;
    private javax.swing.JLabel jlbNom2;
    private javax.swing.JLabel jlbNomMereValue;
    private javax.swing.JLabel jlbNomPereValue;
    private javax.swing.JLabel jlbNomValue;
    private javax.swing.JLabel jlbNumTelValue;
    private javax.swing.JLabel jlbNumTelephone;
    private javax.swing.JLabel jlbPermiDeman;
    private javax.swing.JLabel jlbPermisValue;
    private javax.swing.JLabel jlbdtInscValue;
    private javax.swing.JLabel jlbdtNaissanceValue;
    // End of variables declaration//GEN-END:variables

}
